### PR TITLE
move phpunit.xml to phpunit.xml.dist, tests with composer autoload

### PR DESCRIPTION
**Pull request by gpupo**
Move phpunit.xml to phpunit.xml.dist, tests with composer autoload

### CODE REVIEW

**Comment by duncan3dc** [comment]
Thanks @gpupo

What are the advantages of this change?  Is anything different?

**Comment by gpupo** [comment]
Hi @duncan3dc! The advantage is the use of less programming, files,  and explicitly configuration of phpunit

**Comment by duncan3dc** [comment]
I like the testsuite setting, but I don't think the rest should be added, as that makes it seem like the projects recommended settings, when the project doesn't have any. And autoloading the tests directory is unnecessary.

Good call on renaming to `.dist` too :+1:

**Comment by gpupo** [comment]
autoloading-dev set autoloading of tests only in dev Env

**Comment by duncan3dc** [comment]
But there is nothing to autoload. If you remove that, and strip out the phpunit settings back to the ones required (eg, just `testsuite` and `bootstrap`) I'd be glad to merge this

**Pull request closed without merging**
